AddonId: NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59
Packages:
  - Version: 1.4.5
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2025-11-24
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.4.5/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_4_5.pext
    Changelog:
    - Fixes issue 18, Playnite crashes when trying to add game through the extension
  - Version: 1.4.4
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-11-04
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.4.4/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_4_4.pext
    Changelog:
    - Same functionality as v1.4.3 but reduces NowPlaying_*.pext file size drastically (was 149MB -> now 0.5MB); sorry about the bloated releases (v1.3.6 to v.1.4.3).
    - (github) Adds VS post-build scripting to automatically build + pack 'lean' releases going forward (see previous item for impact)
  - Version: 1.4.3
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-11-01
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.4.3/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_4_3.pext
    Changelog:
    - Fixes bug that prevented write-back of dirty caches during uninstall. Note, uninstall times could increase with this fix (unless you choose 'Never sync settings/game save data' under Settings -> Sync on uninstall).   
    - Fixes bug that can cause Playnite -> Exit to hang if a cache is being installed.
    - Shortens 'Can install?' and 'Install ETA' column names to '⭳ OK?' and '⭳ ETA', resp. 
    - Applies further theme tweaks and support of larger fonts/font sizes, including with progress bars and column auto/minimum width sizing within the game caches / cache roots list view.
    - Adds 'Space Available per cache root' info to the Playnite library view menu for enabling game caching/choosing a root (only when multiple cache roots are defined). 
    - Improves robustness of enable/install/uninstall queue system.
  - Version: 1.4.2
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-10-22
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.4.2/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_4_2.pext
    Changelog:
    - Reworks UI for improved support of larger font sizes. 
      Note, this plugin uses Playnite's 'Normal' font size for most text, 'Large' for subheadings, and 'Large * 1.2' for heading text (by default, these are 14/15/18-pt, resp.)
    - Adds saving/restoring of search text and (cache roots/game caches) list sorting state, and cache roots shown/hidden state when Playnite is exited/restarted.
    - Adds option to hide 'NowPlaying Game Caches' heading when cache roots are hidden, for a more streamlined look (see Settings, by default this is disabled/unchecked). 
    - Fixes sort glyph bug when a sorted list view column is Hidden. 
  - Version: 1.4.1
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-10-08
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.4.1/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_4_1.pext
    Changelog:
    - Adds stylings for FusionX and Stardust (Legacy Layout) themes and applies general tweaks for other themes, too.
    - NowPlaying icon slightly recolored to look better (imo) when scaled down in size. 
    - Adjusts the way average transfer speed (AverageBps) is averaged across cache installs - increases the weight placed on the current install. 
  - Version: 1.4
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-10-01
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.4/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_4.pext
    Changelog:
    - Majorly reworks visuals to improve list view performance and better adopt Theme stylings
    - Adds filtering by game Title to all list views (via SearchBox)
    - Adds live sorting of game caches/cache root list views, while game installs/uninstalls are underway
    - Adds dynamic minimum width to the Status column of the game caches list view; column automatically widens when Status is reporting queued install/uninstalls or when installing w/ a speed limit    
    - Adds settings option to flip orientation of horizontal (hold Shift + mouse wheel) scrolling 
  - Version: 1.3.6
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-09-06
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.3.6/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_3_6.pext
    Changelog:
    - Changes NowPlaying sidebar icon's (inactive/unselected) coloring to now come from Theme's SidebarItem.Foreground property. This addresses Github issue 16.
    - Fixes NowPlaying panel view's cache roots icon to use Theme's Button style coloring
    - Removes Settings option to choose Sidebar Icon color (see previous bullet).
    - Updates to Panel view & Add Game Caches popup list views, which are now by Ascending-order-sorted according to Title/Directory by default. 
  - Version: 1.3.5
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-08-30
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.3.5/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_3_5.pext
    Changelog:
    - Adds support for emulator profiles have more complex arguments than just "{ImagePath}", e.g. '-dvd_path "{ImagePath}" --full-screen'
    - Adds optional 'Uninstall & Disable Combo' command to Playnite's right-click games menus, which uninstalls game cache(s) of the 
      selected game(s) and then disables game caching, in one step. (Settings->General->"Show 'Uninstall cache + Disable caching' combo..." must be checked).
    - Adds ability to install/uninstall game caches of multiple games at once from Playnite's right-click game menus (as can be done from the NowPlaying panel view).
    - Adds optional status/menu tips information to Playnite's right-click game menus (when Settings->General->"Show status/menu tips..." is checked).
    - Adds two color choices for the monochrome NowPlaying icons shown on the Playnite sidebar and with (optional) status/menu tips. 
      (See Settings->General->"Status/menu tips icon color" and "Sidebar icon color..." Lighter/Darker check boxes.)
  - Version: 1.3.4
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-08-12
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.3.4/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_3_4.pext
    Changelog:
    - Adds cache eligibility for games with multiple Playnite platforms checked (which may include user-defined 'dummy' platforms used for filtering), 
      provided they have exactly one of the supported platforms checked (e.g. 'PC (Windows)'). This addresses github issue 14.
  - Version: 1.3.3
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-08-26
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.3.3/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_3_3.pext
    Changelog:
    - Adds dimming of the NowPlaying panel whenever a popup dialog window is displayed, e.g. for adding/editing cache roots or adding game caches.
    - Adds 'Source directory' column to popup window for adding game caches.
    - Adds 'Source directory' column to NowPlaying panel's game caches list.
    - Adds show/hide capability to each column of the the cache roots and game caches lists of the NowPlaying panel; accessible via right-click check boxes when moused over the header row of either list.
    - Fixes case where a Playnite game could be stuck in 'installing' state, when a game cache install (or a queued install) is cancelled. 
  - Version: 1.3.2
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-07-27
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.3.2/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_3_2.pext
    Changelog:
    - Adds saving & restoring of game cache install/queue state if Playnite is restarted while an install is in progress.
  - Version: 1.3.1
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-07-21
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.3.1/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_3_1.pext
    Changelog:
    - Adds PS2, Xbox, GameCube, and Wii to supported emulation platforms.
    - Updates install progress bar color to use current Theme's glyph color.
  - Version: 1.3
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-07-08
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.3/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_3.pext
    Changelog:
    - Adds game caching support for some emulated platforms
      - Sony Playstation 3 (RPCS3)
      - Microsoft Xbox 360 (Xenia)
      - Nintendo Switch (Ryujinx, Yuzu)
    - Adds separate 'Speed' and 'Average Speed' status to the install progress bar
      - Speed - 'current' device transfer speed, based on a 16-second rolling average
      - Average Speed - long-term-average device transfer speed used for ETA calculations, based on ~4-minute rolling average  
  - Version: 1.2.1
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-06-18
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.2.1/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_2_1.pext
    Changelog:
    - Improves consistency, increases (low pass) filtering of cache install speed, duration, and ETA stats; now updated every 1/2 second
    - Adds icons to right-mouse context menus
  - Version: 1.2
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-06-17
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.2/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_2.pext
    Changelog:
    - Improves overall app responsiveness & robustness for games installed on very slow/over the network devices.
    - Improves install ETA accuracy by incorporating a game's average file size.
    - Adds install directory prescan when enabling a game; prompts for confirmation if problematic subdirs are found (e.g. 'bin', 'x64', etc.)
    - Adds optional partial file resume mode (PFR) for over the network cache installations.
    - Adds horizontal mouse wheel+Shift scrolling to list views.
    - Adds support for copying symlinks when installing a cache.
    - Fixes pause/cancel responsiveness when cache install is still in its preparation phase. 
    - Fixes underreported ETA for paused installation where interrupted file is large.
    - Fixes case where game could be enabled multiple times.
    - Fixes game eligibility test (typo fix).
  - Version: 1.1
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-06-03
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.1/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_1.pext
    Changelog:
    - Added a create directory button to the 'add cache root' popup window and improved directory/device sanity checking.
    - Added column sorting and clear search text button to the 'enable game caching' dialog.
    - Added column sorting to the cache roots list.
    - Fixed mouse-wheel scrolling when hovering over the cache roots/game caches lists.
    - Added minimum column width sizing to cache roots/game caches/eligible games lists.
    - Fixed handling of installation directory when it has a trailing slash.
    - Fixed deletion of game cache if it contains read only files. 
  - Version: 1.0.0
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-05-31
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v1.0.0/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_1_0_0.pext
    Changelog:
    - "It's go time... (fingers crossed)"
  - Version: 0.9.2
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-05-29
    PackageUrl: https://github.com/gittromney/Playnite-NowPlaying/releases/download/v0.9.2/NowPlaying_0dbead64-b7ed-47e5-904c-0ccdb5d5ff59_0_9_2.pext
    Changelog:
    - "Initial, beta release"